### ISSUE TITLE
Build Card Component

### ISSUE THREAD

**Issue by blakewilson** [Fran-A-Dev/climber-coder-finder#14]
When a user clicks on a emoji for climbing/food/beverage/gear, display card component with:
* Name
* Location Name
* Lat/long
* etc

**Comment by Fran-A-Dev** [comment]
Hey Blake, I made a card component, check it out - I need advice on a few things: where to place this in our main index.tsx file and also just check if it is correctly coded.  I will create a css module for it as well

**Comment by blakewilson** [comment]
Closed via #13
